package com.mycompany.pracitca3eva;

import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLightLaf;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Comparator;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

/**
 *
 * @author canmonal
 */
public class GUI_Principal extends javax.swing.JFrame {

    private String nombre;    //Nombre de jugador
    private int contadorTotalSegundos; // Variable para almacenar el tiempo total en segundos

    private ArrayList<RegistroJugador> jugadores = new ArrayList<>(); //Creo un ranking para almacenar los tiempos

    private int botonesDeshabilitados; //Indica el fin del juego    (cuando termina los 4 juegos se muestra el ranking)

    public GUI_Principal() {
        initComponents();        
        //Pongo el Look And Feel FlatLightLaf por defecto nada mas iniciar
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
            SwingUtilities.updateComponentTreeUI(this);
        } catch (Exception e) {
            e.printStackTrace();
        }
        setFrame();
    }

    private void setFrame() {
        setTitle("Empieza el juego");
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        jButtonMostrarRanking.setVisible(false); //Deshabilito el ranking hasta el final        
        jButtonCerrar.setVisible(false); //Deshabilito el botón de cerrar juego hasta el final

        JOptionPane.showMessageDialog(this, "<html>Bienvenido a la <b>GYMKANA</b> de los MUSEOS</html>");
        String mensaje = "<html>Antes de comenzar, debes saber varias cosas:"
                + "<ol>"
                + "<li>La gymkana consta de 4 juegos a superar"
                + "<li>Hasta que no los superes, no podrás salir"
                + "<li>Tendrás un contador que contabilice el tiempo en superar todos."
                + "</ol></html>";

        JOptionPane.showMessageDialog(rootPane, mensaje);

        boolean mostrarDialogo = true; //Creo una variable para que tenga que ingresar un nombre y no pueda darle a la X (Manejar también excepción)
        while (mostrarDialogo) {
            nombre = JOptionPane.showInputDialog(rootPane, "Por último, introduce el nombre del jugador: ");
            if (nombre == null || nombre.isEmpty()) {
                mostrarDialogo = true;  // Vuelvo a mostrar el diálogo para pedir el nombre                
            } else {
                mostrarDialogo = false; // Salgo del bucle
            }
        }
        JOptionPane.showMessageDialog(null, "<html><h1><b>¡QUE EMPIECE EL JUEGO :)!</b></h1></html>");
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelQuienLoHizo = new javax.swing.JPanel();
        jLabelQuienLoHizo = new javax.swing.JLabel();
        jButtonIniciarQuienLoHizo = new javax.swing.JButton();
        jPanelTiempo = new javax.swing.JPanel();
        jLabelTiempo = new javax.swing.JLabel();
        jPanelGregorioFernandez = new javax.swing.JPanel();
        jLabelGregorioFer = new javax.swing.JLabel();
        jButtonIniciarGregorioFernandez = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanelRankingCerrarJuego = new javax.swing.JPanel();
        jButtonMostrarRanking = new javax.swing.JButton();
        jButtonCerrar = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jPanelColocarMapa = new javax.swing.JPanel();
        jLabelColocarMapa = new javax.swing.JLabel();
        jButtonIniciarColocarMapa = new javax.swing.JButton();
        jPanelCambiarEstilo = new javax.swing.JPanel();
        jLabelCambiar = new javax.swing.JLabel();
        jButtonClaro = new javax.swing.JButton();
        jButtonOscuro = new javax.swing.JButton();
        jPanelVerdaderoFalso = new javax.swing.JPanel();
        jLabelVFMuseos = new javax.swing.JLabel();
        jButtonIniciarVerdaderoFalso = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(3, 2));

        jPanelQuienLoHizo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelQuienLoHizo.setText("¿Quién Lo hizo?");
        jLabelQuienLoHizo.setAlignmentX(21.0F);
        jLabelQuienLoHizo.setAlignmentY(20.0F);
        jPanelQuienLoHizo.add(jLabelQuienLoHizo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jButtonIniciarQuienLoHizo.setText("Iniciar");
        jButtonIniciarQuienLoHizo.setAlignmentX(10.0F);
        jButtonIniciarQuienLoHizo.setAutoscrolls(true);
        jButtonIniciarQuienLoHizo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIniciarQuienLoHizoActionPerformed(evt);
            }
        });
        jPanelQuienLoHizo.add(jButtonIniciarQuienLoHizo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        getContentPane().add(jPanelQuienLoHizo);

        jPanelTiempo.add(jLabelTiempo);

        getContentPane().add(jPanelTiempo);

        jPanelGregorioFernandez.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelGregorioFer.setText("Gregorio Fernández");
        jLabelGregorioFer.setAlignmentX(21.0F);
        jLabelGregorioFer.setAlignmentY(20.0F);
        jPanelGregorioFernandez.add(jLabelGregorioFer, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jButtonIniciarGregorioFernandez.setText("Iniciar");
        jButtonIniciarGregorioFernandez.setAlignmentX(10.0F);
        jButtonIniciarGregorioFernandez.setAutoscrolls(true);
        jButtonIniciarGregorioFernandez.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIniciarGregorioFernandezActionPerformed(evt);
            }
        });
        jPanelGregorioFernandez.add(jButtonIniciarGregorioFernandez, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        getContentPane().add(jPanelGregorioFernandez);
        getContentPane().add(jPanel6);

        jButtonMostrarRanking.setText("Ranking");
        jButtonMostrarRanking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMostrarRankingActionPerformed(evt);
            }
        });
        jPanelRankingCerrarJuego.add(jButtonMostrarRanking);

        jButtonCerrar.setText("Cerrar Juego");
        jButtonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarActionPerformed(evt);
            }
        });
        jPanelRankingCerrarJuego.add(jButtonCerrar);

        getContentPane().add(jPanelRankingCerrarJuego);
        getContentPane().add(jPanel9);

        jPanelColocarMapa.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelColocarMapa.setText("Colocar en el Mapa");
        jLabelColocarMapa.setAlignmentX(21.0F);
        jLabelColocarMapa.setAlignmentY(20.0F);
        jPanelColocarMapa.add(jLabelColocarMapa, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jButtonIniciarColocarMapa.setText("Iniciar");
        jButtonIniciarColocarMapa.setAlignmentX(10.0F);
        jButtonIniciarColocarMapa.setAutoscrolls(true);
        jButtonIniciarColocarMapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIniciarColocarMapaActionPerformed(evt);
            }
        });
        jPanelColocarMapa.add(jButtonIniciarColocarMapa, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        getContentPane().add(jPanelColocarMapa);

        jLabelCambiar.setText("Cambiar Estilo Ventana:");

        jButtonClaro.setText("Claro");
        jButtonClaro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClaroActionPerformed(evt);
            }
        });

        jButtonOscuro.setText("Oscuro");
        jButtonOscuro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOscuroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCambiarEstiloLayout = new javax.swing.GroupLayout(jPanelCambiarEstilo);
        jPanelCambiarEstilo.setLayout(jPanelCambiarEstiloLayout);
        jPanelCambiarEstiloLayout.setHorizontalGroup(
            jPanelCambiarEstiloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCambiarEstiloLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabelCambiar))
            .addGroup(jPanelCambiarEstiloLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jButtonClaro)
                .addGap(5, 5, 5)
                .addComponent(jButtonOscuro))
        );
        jPanelCambiarEstiloLayout.setVerticalGroup(
            jPanelCambiarEstiloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCambiarEstiloLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabelCambiar)
                .addGap(5, 5, 5)
                .addGroup(jPanelCambiarEstiloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonClaro)
                    .addComponent(jButtonOscuro)))
        );

        getContentPane().add(jPanelCambiarEstilo);

        jPanelVerdaderoFalso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelVFMuseos.setText("Verdadero / Falso Museos");
        jLabelVFMuseos.setAlignmentX(21.0F);
        jLabelVFMuseos.setAlignmentY(20.0F);
        jPanelVerdaderoFalso.add(jLabelVFMuseos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jButtonIniciarVerdaderoFalso.setText("Iniciar");
        jButtonIniciarVerdaderoFalso.setAlignmentX(10.0F);
        jButtonIniciarVerdaderoFalso.setAutoscrolls(true);
        jButtonIniciarVerdaderoFalso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIniciarVerdaderoFalsoActionPerformed(evt);
            }
        });
        jPanelVerdaderoFalso.add(jButtonIniciarVerdaderoFalso, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        getContentPane().add(jPanelVerdaderoFalso);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIniciarVerdaderoFalsoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIniciarVerdaderoFalsoActionPerformed
        Verdadero_Falso vf= new Verdadero_Falso(this);
        vf.setVisible(true);
        jButtonIniciarVerdaderoFalso.setEnabled(false);
    }//GEN-LAST:event_jButtonIniciarVerdaderoFalsoActionPerformed

    private void jButtonIniciarQuienLoHizoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIniciarQuienLoHizoActionPerformed
        QuienLoHizo qlh = new QuienLoHizo(this);
        if (!qlh.isActive())
            jButtonIniciarQuienLoHizo.setEnabled(false);
    }//GEN-LAST:event_jButtonIniciarQuienLoHizoActionPerformed

    private void jButtonIniciarGregorioFernandezActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIniciarGregorioFernandezActionPerformed
        GregorioFernandez gf = new GregorioFernandez(this);
        gf.setVisible(true);
        jButtonIniciarGregorioFernandez.setEnabled(false);        
    }//GEN-LAST:event_jButtonIniciarGregorioFernandezActionPerformed

    private void jButtonMostrarRankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMostrarRankingActionPerformed
        verRanking();
    }//GEN-LAST:event_jButtonMostrarRankingActionPerformed

    private void jButtonIniciarColocarMapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIniciarColocarMapaActionPerformed
        ColocaEnElMapa colocaEnElMapa = new ColocaEnElMapa(this);
        jButtonIniciarColocarMapa.setEnabled(false);        
    }//GEN-LAST:event_jButtonIniciarColocarMapaActionPerformed

    private void jButtonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCerrarActionPerformed

    //Creo botones jButtonClaro y jButtonOscuro para cambiar color de ventana y colores de texto
    private void jButtonClaroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClaroActionPerformed
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
            SwingUtilities.updateComponentTreeUI(this);
            cambiarColorTexto(java.awt.Color.BLACK);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButtonClaroActionPerformed

    //Método para cambiar el color si elige claro o oscuro
    private void cambiarColorTexto(java.awt.Color color) {
        // Cambiar el color del texto de los componentes deseados
        jLabelQuienLoHizo.setForeground(color);
        jLabelTiempo.setForeground(color);
        jLabelGregorioFer.setForeground(color);
        jLabelColocarMapa.setForeground(color);
        jLabelCambiar.setForeground(color);
        jLabelVFMuseos.setForeground(color);
    }

    private void jButtonOscuroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOscuroActionPerformed
        try {
            UIManager.setLookAndFeel(new FlatDarkLaf());
            SwingUtilities.updateComponentTreeUI(this);
            cambiarColorTexto(java.awt.Color.WHITE);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButtonOscuroActionPerformed

    //Método para aumentar el contador total, LO HAGO PÚBLICO PARA PODER UTILIZARLO EN TODOS LOS JUEGOS
public void aumentarContadorTotal(int segundos) {
    contadorTotalSegundos += segundos; // Aumentar el contador total con los segundos del juego actual        
    String tiempoFormateado = getTiempoFormateado(contadorTotalSegundos); //Cambio los segundos a hh:mm:ss
    jLabelTiempo.setText("Tiempo total: " + tiempoFormateado);
    botonesDeshabilitados++; // Incrementar el contador de botones deshabilitados

    if (botonesDeshabilitados == 4) { // Si los 4 botones están deshabilitados
        jButtonMostrarRanking.setVisible(true); // Mostrar el botón de mostrar ranking           
        jButtonCerrar.setVisible(true); //Mostrar el botón de cerrar Juego
        agregarJugadorAlArchivo(nombre, contadorTotalSegundos); // Agregar
    }
}


    //Métodop para modificar tiempo a hh:mm:ss
    private String getTiempoFormateado(int segundos) {
        int horas = segundos / 3600; //Paso segundos a horas
        int minutos = (segundos % 3600) / 60; //Paso segundos a minutos
        int segs = segundos % 60;
        // Crear un objeto LocalTime con la hora
        LocalTime tiempo = LocalTime.of(horas, minutos, segs);
        // Crear un formateador de fecha y hora en formato hh:mm:ss
        DateTimeFormatter formateador = DateTimeFormatter.ofPattern("HH:mm:ss");
        // Formatear el tiempo en el formato deseado
        return tiempo.format(formateador);
    }

    //Método para agregar un jugador (nombre y tiempo) al ranking de tiempos
    private void agregarJugadorAlArchivo(String nombre, int tiempo) {
        try {
            FileWriter fw = new FileWriter("jugadores.txt", true);
            BufferedWriter bw = new BufferedWriter(fw);

            // Escribir el nombre y el tiempo del jugador en una nueva línea del archivo
            bw.write(nombre + "," + tiempo);
            bw.newLine();

            bw.close(); // Cerrar el archivo
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    //Método para ver el ranking de tiempos
    private void verRanking() {
        try {
            FileReader fr = new FileReader("jugadores.txt");
            BufferedReader br = new BufferedReader(fr);
            String line;
            while ((line = br.readLine()) != null) { // Se lee cada línea del archivo y se separa en utilizando la coma como delimitador
                String[] parts = line.split(",");
                if (parts.length == 2) { //Compruebo que la linea tiene nombre y tiempo (2 partes)
                    String nombre = parts[0];
                    int tiempo = Integer.parseInt(parts[1]);
                    jugadores.add(new RegistroJugador(nombre, tiempo)); // Creo un objeto RegistroJugador con el nombre y tiempo leídos y se agrega a la lista de jugadores
                }
            }

            br.close();

            //Ordeno los jugadores por tiempo en orden ascendente
            jugadores.sort(Comparator.comparingInt(RegistroJugador::getTiempo));
            StringBuilder sb = new StringBuilder();
            int posicion = 1;

            //Recorro la lista de jugadores yhago una cadena de texto con el ranking
            for (RegistroJugador jugador : jugadores) {
                sb.append(posicion).append(". ").append(jugador.getNombre()).append(" - ").append(getTiempoFormateado(jugador.getTiempo())).append("\n");
                posicion++;
            }

            //Muestro el ranking en un cuadro de diálogo
            JOptionPane.showMessageDialog(this, sb.toString(), "Ranking", JOptionPane.INFORMATION_MESSAGE);

        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new GUI_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCerrar;
    private javax.swing.JButton jButtonClaro;
    private javax.swing.JButton jButtonIniciarColocarMapa;
    private javax.swing.JButton jButtonIniciarGregorioFernandez;
    private javax.swing.JButton jButtonIniciarQuienLoHizo;
    private javax.swing.JButton jButtonIniciarVerdaderoFalso;
    private javax.swing.JButton jButtonMostrarRanking;
    private javax.swing.JButton jButtonOscuro;
    private javax.swing.JLabel jLabelCambiar;
    private javax.swing.JLabel jLabelColocarMapa;
    private javax.swing.JLabel jLabelGregorioFer;
    private javax.swing.JLabel jLabelQuienLoHizo;
    private javax.swing.JLabel jLabelTiempo;
    private javax.swing.JLabel jLabelVFMuseos;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelCambiarEstilo;
    private javax.swing.JPanel jPanelColocarMapa;
    private javax.swing.JPanel jPanelGregorioFernandez;
    private javax.swing.JPanel jPanelQuienLoHizo;
    private javax.swing.JPanel jPanelRankingCerrarJuego;
    private javax.swing.JPanel jPanelTiempo;
    private javax.swing.JPanel jPanelVerdaderoFalso;
    // End of variables declaration//GEN-END:variables
}
